<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <LangVersion>12</LangVersion>
        <TargetFramework>net4.8</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <Reference Include="Exiled.API">
            <HintPath>$(EXILED_REFERENCES)\Exiled.API.dll</HintPath>
        </Reference>
        <Reference Include="Exiled.CreditTags">
            <HintPath>$(EXILED_REFERENCES)\Exiled.CreditTags.dll</HintPath>
        </Reference>
        <Reference Include="Exiled.CustomItems">
            <HintPath>$(EXILED_REFERENCES)\Exiled.CustomItems.dll</HintPath>
        </Reference>
        <Reference Include="Exiled.CustomRoles">
            <HintPath>$(EXILED_REFERENCES)\Exiled.CustomRoles.dll</HintPath>
        </Reference>
        <Reference Include="Exiled.Events">
            <HintPath>$(EXILED_REFERENCES)\Exiled.Events.dll</HintPath>
        </Reference>
        <Reference Include="Exiled.Loader">
            <HintPath>$(EXILED_REFERENCES)\Exiled.Loader.dll</HintPath>
        </Reference>
        <Reference Include="Exiled.Permissions">
            <HintPath>$(EXILED_REFERENCES)\Exiled.Permissions.dll</HintPath>
        </Reference>
        <Reference Include="Exiled.Starter">
            <HintPath>$(EXILED_REFERENCES)\Exiled.Starter.dll</HintPath>
        </Reference>
        <Reference Include="FLXLib">
            <HintPath>$(EXILED_REFERENCES)\FLXLib.dll</HintPath>
        </Reference>
        <Reference Include="LabApi">
            <HintPath>$(EXILED_REFERENCES)\LabApi.dll</HintPath>
        </Reference>
        <Reference Include="Newtonsoft.Json">
            <HintPath>$(EXILED_REFERENCES)\Newtonsoft.Json.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine" HintPath="$(EXILED_REFERENCES)\UnityEngine.dll"/>
        <Reference Include="UnityEngine.AnimationModule" HintPath="$(EXILED_REFERENCES)\UnityEngine.AnimationModule.dll"/>
        <Reference Include="UnityEngine.AudioModule">
            <HintPath>$(EXILED_REFERENCES)\UnityEngine.AudioModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.CoreModule" HintPath="$(EXILED_REFERENCES)\UnityEngine.CoreModule.dll"/>
        <Reference Include="UnityEngine.AssetBundleModule" HintPath="$(EXILED_REFERENCES)\UnityEngine.AssetBundleModule.dll"/>
        <Reference Include="UnityEngine.PhysicsModule" HintPath="$(EXILED_REFERENCES)\UnityEngine.PhysicsModule.dll"/>
        <Reference Include="Unity.TextMeshPro" HintPath="$(EXILED_REFERENCES)\Unity.TextMeshPro.dll"/>
        <Reference Include="Mirror" HintPath="$(EXILED_REFERENCES)\Mirror.dll"/>
        <Reference Include="Assembly-CSharp" HintPath="$(EXILED_REFERENCES)\Assembly-CSharp-Publicized.dll"/>
        <Reference Include="Assembly-CSharp-firstpass" HintPath="$(EXILED_REFERENCES)\Assembly-CSharp-firstpass.dll"/>
        <Reference Include="CommandSystem.Core" HintPath="$(EXILED_REFERENCES)\CommandSystem.Core.dll"/>
        <Reference Include="WeightedRandomizer">
            <HintPath>$(EXILED_REFERENCES)\WeightedRandomizer.dll</HintPath>
        </Reference>
        <Reference Include="YamlDotNet" HintPath="$(EXILED_REFERENCES)\YamlDotNet.dll"/>
        <Reference Include="NorthwoodLib" HintPath="$(EXILED_REFERENCES)\NorthwoodLib.dll"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Lib.Harmony" Version="2.3.6"/>
    </ItemGroup>

    <Target Name="PostBuild" AfterTargets="PostBuildEvent">
        <Exec Command="
    copy /Y &quot;$(TargetPath)&quot; &quot;$(EXILED)\Plugins\&quot;
    copy /Y &quot;$(TargetPath)&quot; &quot;$(EXILED_REFERENCES)\&quot;
  "/>
    </Target>

</Project>
